DungeonResource.Web/Controllers/BookController.cs
using DungeonResource.Components.Domain.Book;
using DungeonResource.Components.Domain.Spell;
using DungeonResource.Components.Service.Abstract;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DungeonResource.Web.Controllers
{
    public class BookController : Controller
    {
        /// <summary>
        /// Handles the business logic for the interactions with books
        /// </summary>
        private readonly IBookService _bookService;

        /// <summary>
        /// ctor
        /// </summary>
        /// <param name="bookService"></param>
        public BookController(IBookService bookService)
        {
            _bookService = bookService;
        }

        //
        // GET: /Book/
        public ActionResult Index()
        {
            var books = _bookService.ReadAll();
            return View(books.OrderBy(p => p.Title));
        }
	}
}

DungeonResource.Web/Controllers/DomainController.cs
using DungeonResource.Components.Domain.Domain;
using DungeonResource.Components.Repository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DungeonResource.Web.Controllers
{
    public class DomainController : Controller
    {

        private readonly IGenericRepository<Domain> _genericRepository;

        /// <summary>
        ///     ctor
        /// </summary>
        public DomainController(IGenericRepository<Domain> genericRepository)
        {
            _genericRepository = genericRepository;
        }

        //
        // GET: /Domain/
        public ActionResult Index()
        {
            var domains = _genericRepository.Read();

            return View(domains);
        }
	}
}

DungeonResource.Web/Controllers/SkillController.cs
using DungeonResource.Components.Domain.Skill;
using DungeonResource.Components.Repository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DungeonResource.Web.Controllers
{
    public class SkillController : Controller
    {
        private readonly IGenericRepository<Skill> _genericRepository;

        /// <summary>
        ///     ctor
        /// </summary>
        public SkillController(IGenericRepository<Skill> genericRepository)
        {
            _genericRepository = genericRepository;
        }

        //
        // GET: /Skill/
        public ActionResult Index()
        {
            var skills = _genericRepository.Read();

            return View(skills);
        }
	}
}

DungeonResource.Web/Controllers/UserController.cs
using DungeonResource.Components.Domain.Book;
using DungeonResource.Components.Domain.Spell;
using DungeonResource.Components.Service.Abstract;
using DungeonResource.Web.Models.User;
using SimpleCrypto;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace DungeonResource.Web.Controllers
{
    public class UserController : Controller
    {

        private readonly ICryptoService _cryptoService;
        private readonly IUserService _userService;

        /// <summary>
        /// ctor
        /// </summary>
        /// <param name="cryptoService"></param>
        /// <param name="userservice"></param>
        public UserController(ICryptoService cryptoService, IUserService userservice)
        {
            _cryptoService = cryptoService;
            _userService = userservice;
        }

        public ActionResult Register()
        {
            //return View();

            // Added to eliminate open registration
            return RedirectToAction("Index", "Spell");
        }

        [HttpPost]
        public ActionResult Register(RegistrationViewModel userDetails)
        {
            //if(ModelState.IsValid && !_userService.UserExists(userDetails.Username))
            //{
            //    // Generate a password hash plus the salt
            //    var hashedPassword = _cryptoService.Compute(userDetails.Password);
            //    var passwordSalt = _cryptoService.Salt;

            //    // Transfer the view Model data to a domain object
            //    var user = new User
            //    {
            //        Username = userDetails.Username,
            //        Email = userDetails.EMail,
            //        DateCreated = DateTime.Now,
            //        DateLastLogin = DateTime.Now,
            //        PasswordHash = hashedPassword,
            //        PasswordSalt = passwordSalt
            //    };

            //    // Add the user to the database
            //    _userService.CreateUser(user);

            //    // Set up a cookie verifying the user is logged in
            //    FormsAuthentication.SetAuthCookie(user.Username, true);

            //    return RedirectToAction("Index", "Spell");
            //}

            //return View(userDetails);

            // Added to eliminate open registration
            return RedirectToAction("Index", "Spell");
        }

        [HttpGet]
        public ActionResult LogIn()
        {
            return View();
        }

        [HttpPost]
        public ActionResult LogIn(LogInViewModel userDetails)
        {
            var valid = _userService.AuthenticateUser(userDetails.Username, userDetails.Password);

            if (valid)
            {
                // Set up a cookie verifying the user is logged in
                FormsAuthentication.SetAuthCookie(userDetails.Username, true);
                //WebSecurity.Login(userDetails.Username, userDetails.Password);

                return RedirectToAction("Index", "Spell");
            }

            return View(userDetails);
        }

        public ActionResult LogOut()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("Index", "Spell");
        }
    }
}

DungeonResource.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Spellbook</title>

    @Scripts.Render("~/bundles/libraries")
    @Styles.Render("~/Content/css");

    <style type="text/css">
        body {
            padding-top: 60px;
            padding-bottom: 40px;
            background-color: #f5f5f5;
            background-image: url('/Content/images/irongrip.png');
        }

        .form-signin,
        .form-signin1 {
            padding: 19px 29px 29px;
            margin: 0 auto 20px;
            background-color: #fff;
            border: 1px solid #e5e5e5;
            -webkit-border-radius: 5px;
            -moz-border-radius: 5px;
            border-radius: 5px;
            -webkit-box-shadow: 0 1px 2px rgba(0,0,0,.05);
            -moz-box-shadow: 0 1px 2px rgba(0,0,0,.05);
            box-shadow: 0 1px 2px rgba(0,0,0,.05);
        }

        .form-signin1 {
            max-width: 300px;
        }

        .accordion-heading a {
            font-weight: bold;
        }

        #wrap > .container {
            padding-top: 60px;
        }
    </style>

    <script>
        (function (i, s, o, g, r, a, m) {
            i['GoogleAnalyticsObject'] = r; i[r] = i[r] || function () {
                (i[r].q = i[r].q || []).push(arguments)
            }, i[r].l = 1 * new Date(); a = s.createElement(o),
            m = s.getElementsByTagName(o)[0]; a.async = 1; a.src = g; m.parentNode.insertBefore(a, m)
        })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');

        ga('create', 'UA-40287478-1', 'dungeonresource.com');
        ga('send', 'pageview');

    </script>

</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href='@Url.Action("Index", "Spell")'>Dungeon Resource</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <li><a href='@Url.Action("Index", "Spell")'>Spells</a></li>
                    <li><a href='@Url.Action("Index", "Domain")'>Domains</a></li>
                    <li><a href='@Url.Action("Index", "Skill")'>Skills</a></li>
                    <li><a href='@Url.Action("Index", "Book")'>Books</a></li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">About <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li><a href="https://github.com/holymoo/DungeonResource">GitHub</a></li>
                            <li><a href="https://github.com/holymoo/DungeonResource/issues">Issue Tracking</a></li>
                        </ul>
                    </li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    @if (!Request.IsAuthenticated)
                    {
                        <li><a href='@Url.Action("LogIn", "User")'>Log In</a></li>
                        @*<li class="divider-vertical"></li>
                            <li><a href='@Url.Action("Register", "User")'>Register</a></li> *@
                    }
                    else
                    {
                        <li><a href='@Url.Action("LogOut", "User")'>Log Out</a></li>
                    }
                </ul>
            </div><!-- /.navbar-collapse -->
        </div>
    </nav>

    <div class="container">
        @RenderBody()
    </div>

</body>
</html>