DungeonResource.Web/Controllers/Api/SpellController.cs
using DungeonResource.Components.Domain.Spell;
using DungeonResource.Components.Service.Abstract;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;

namespace DungeonResource.Web.Controllers.Api
{
    /// <summary>
    /// Handles restful spell operations
    /// </summary>
    public class SpellController : ApiController
    {
        /// <summary>
        /// Handles the management of the spell data
        /// </summary>
        private readonly ISpellService _spellService;

        /// <summary>
        /// ctor
        /// </summary>
        /// <param name="spellService"></param>
        public SpellController(ISpellService spellService)
        {
            _spellService = spellService;
        }
        
        /// <summary>
        /// Reads a spell out of the database
        /// </summary>
        /// <param name="id">
        /// The UID for the spell
        /// </param>
        /// <returns>
        /// The data associated with a single spell
        /// </returns>
        public Spell Get(int id)
        {
            return _spellService.ReadSpell(id);
        }
    }
}

DungeonResource.Web/Controllers/SpellController.cs
using DungeonResource.Components.Domain.Book;
using DungeonResource.Components.Domain.Spell;
using DungeonResource.Components.Service.Abstract;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DungeonResource.Web.Controllers
{
    public class SpellController : Controller
    {
        private ISpellService _spellService;
        private ILogService _logService;

        public SpellController(ISpellService spellService, ILogService logService)
        {
            _spellService = spellService;
            _logService = logService;
        }

        public ActionResult Index()
        {
            var someSpells = _spellService.ReadAllSpells();

            return View(someSpells);
        }

        public ActionResult Details(int id)
        {
            var someSpell = _spellService.ReadSpell(id);

            return View(someSpell);
        }

        [HttpGet]
        public ActionResult Create()
        {
            if (Request.IsAuthenticated)
            {
                var someSpell = new Spell();
                someSpell.SpellLevels = new List<SpellLevel>
                {
                    new SpellLevel { SpellClass = "Wizard", Level = 1}
                };
                someSpell.Range = SpellRange.Self;
                return View(someSpell);
            }

            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult Create(Spell value)
        {
            // Check if the user is logged in
            if (Request.IsAuthenticated)
            {
                // Clean up the spell input
                foreach (var someClass in value.SpellLevels)
                {
                    someClass.SpellClass = someClass.SpellClass.TrimEnd(" ".ToCharArray());
                    someClass.SpellClass = someClass.SpellClass.TrimStart(" ".ToCharArray());
                }

                // Enter in the user data who created the spell
                value.Editor = User.Identity.Name;
                value.LastEdited = DateTime.Now;

                // Add the spell to the database
                _spellService.CreateSpell(value);
            }

            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Update(int id)
        {
            if (Request.IsAuthenticated)
            {
                var someSpell = _spellService.ReadSpell(id);
                return View(someSpell);
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult Update(Spell value)
        {
            if (Request.IsAuthenticated)
            {
                // Clean up the spell input
                foreach (var someClass in value.SpellLevels)
                {
                    someClass.SpellClass = someClass.SpellClass.TrimEnd(" ".ToCharArray());
                    someClass.SpellClass = someClass.SpellClass.TrimStart(" ".ToCharArray());
                }

                // Enter in the user data who created the spell
                value.Editor = User.Identity.Name;
                value.LastEdited = DateTime.Now;

                _spellService.UpdateSpell(value);
                return View(value);
            }

            return RedirectToAction("Index");
        }

        public ActionResult Delete(int id)
        {
            if (Request.IsAuthenticated)
            {
                _spellService.DeleteSpell(id);
            }
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult AddReference(Spell spell)
        {
            return View(spell);
        }

        [HttpPost]
        public ActionResult AddReference(Spell spell, Reference reference)
        {
            // Check if the user is logged in
            if (Request.IsAuthenticated)
            {
                // Validate reference
                if (true)
                {
                    // Add reference to spell
                    spell.BookReferences.Add(reference);

                    // Update spell in database
                    _spellService.UpdateSpell(spell);

                    // Send the user back to the details page to see their update
                    return RedirectToAction("Details", spell.Id);
                }
                else
                {
                    // If the reference is not valid,
                    // report it to the user
                    return View();
                }
            }

            return RedirectToAction("Index");
        }
	}
}

DungeonResource.Web/Views/Spell/Create.cshtml
@using DungeonResource.Web.Models
@model DungeonResource.Components.Domain.Spell.Spell

@{
    ViewBag.Title = "Create";
}

<div class="form-signin" ng-app="myApp" ng-controller="CreateSpellController">

    <h2>Create Spell</h2>

    <br />

    <form role="form" name="form">

        @*Spell Name*@
        <div class="form-group" ng-class="{'has-error': (form.spellName.$dirty && form.spellName.$invalid)}">
            <div>
                <label for="spellName">Spell Name</label>
                <span ng-show="form.spellName.$dirty && form.spellName.$invalid" class="label label-danger">Please Enter a Spell Name</span>
            </div>
            <input type="text"
                   class="form-control"
                   name="spellName"
                   id="spellName"
                   placeholder="Enter spell name"
                   ng-model="spell.Name"
                   required>
        </div>

        @*Target*@
        <div class="form-group" ng-class="{'has-error': (form.spellTarget.$dirty && form.spellTarget.$invalid)}">
            <div>
                <label for="spellTarget">Target</label>
                <span ng-show="form.spellTarget.$dirty && form.spellTarget.$invalid" class="label label-danger">Please Enter a Target</span>
            </div>
            <input type="text"
                   class="form-control"
                   name="spellTarget"
                   id="spellTarget"
                   placeholder="Enter spell target"
                   ng-model="spell.Targets"
                   required>
        </div>

        @*Casting Time*@
        <div class="form-group" ng-class="{'has-error': (form.spellCastingTime.$dirty && form.spellCastingTime.$invalid)}">
            <div>
                <label for="spellCastingTime">Casting Time</label>
                <span ng-show="form.spellCastingTime.$dirty && form.spellCastingTime.$invalid" class="label label-danger">Please Enter a Casting Time</span>
            </div>
            <input type="text" class="form-control" name="spellCastingTime" id="spellCastingTime" placeholder="Enter casting time" ng-model="spell.CastingTime" required>
        </div>

        @*Duration*@
        <div class="form-group" ng-class="{'has-error': (form.spellDuration.$dirty && form.spellDuration.$invalid)}">
            <div>
                <label for="spellDuration">Duration</label>
                <span ng-show="form.spellDuration.$dirty && form.spellDuration.$invalid" class="label label-danger">Please Enter a Spell Duration</span>
            </div>
            <input type="text" class="form-control" name="spellDuration" id="spellDuration" placeholder="Enter spell duration" ng-model="spell.Duration" required>
        </div>

        @*Range*@
        <div class="form-group">
            <div>
                <label>Spell Range</label>
            </div>
            <div class="btn-group">
                <label class="btn btn-default">
                    <input type="radio" name="spellRange" data-ng-model="spell.Range" value="0"> Self
                </label>
                <label class="btn btn-default">
                    <input type="radio" name="spellRange" data-ng-model="spell.Range" value="1"> Touch
                </label>
                <label class="btn btn-default">
                    <input type="radio" name="spellRange" data-ng-model="spell.Range" value="2"> Close
                </label>
                <label class="btn btn-default">
                    <input type="radio" name="spellRange" data-ng-model="spell.Range" value="3"> Medium
                </label>
                <label class="btn btn-default">
                    <input type="radio" name="spellRange" data-ng-model="spell.Range" value="4"> Long
                </label>
            </div>
        </div>

        @*Attributes*@
        <div class="form-group">
            <div>
                <label for="spellImportant">Important</label>
            </div>
            <div class="btn-group" id="spellImportant">
                <label class="btn btn-default">
                    <input ng-model="spell.SpellResistance" type="checkbox"> Spell Resistance
                </label>
                <label class="btn btn-default">
                    <input ng-model="spell.SavingThrow" type="checkbox"> Saving Throw
                </label>
            </div>
        </div>

        @*Components*@
        <div class="form-group">
            <div>
                <label for="spellComponents">Components</label>
            </div>
            <div class="btn-group" id="spellComponents">
                <label class="btn btn-default">
                    <input ng-model="spell.Verbal" type="checkbox"> Verbal
                </label>
                <label class="btn btn-default">
                    <input ng-model="spell.Somatic" type="checkbox"> Somatic
                </label>
                <label class="btn btn-default">
                    <input ng-model="spell.Material" type="checkbox"> Material
                </label>
                <label class="btn btn-default">
                    <input ng-model="spell.Focus" type="checkbox"> Focus
                </label>
            </div>
        </div>

        @*Class Levels*@
        <div class="form-group">
            <div>
                <label for="spellClassLevels">Classes</label>
            </div>
            <table class="table table-striped table-hover">
                <thead>
                    <tr>
                        <th>Class Name</th>
                        <th>Level</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    <tr ng-repeat="spellLevel in spell.SpellLevels">
                        <td>{{spellLevel.SpellClass}}</td>
                        <td>{{spellLevel.Level}}</td>
                        <td><a href="" class="btn btn-default" ng-click="remove(spell.SpellLevels, $index)">Remove</a></td>
                    </tr>
                </tbody>
            </table>
        </div>

        <div class="form-group">
            <div class="form-inline">
                <div class="form-group">
                    <input class="form-control" type="text" id="className" placeholder="Class Name" ng-model="spellClass" />
                </div>
                <div class="form-group">
                    <input class="form-control" type="number" id="spellLevel" placeholder="Class Level" ng-model="spellLevel" />
                </div>
                <a href="" class="btn btn-default" ng-click="addSpellLevel()">Add</a>
            </div>
        </div>

        @*Description*@
        <div class="form-group" ng-class="{'has-error': (form.spellDescription.$dirty && form.spellDescription.$invalid)}">
            <div>
                <label for="spellDescription">Description</label>
                <span ng-show="form.spellDescription.$dirty && form.spellDescription.$invalid" class="label label-danger">Please Enter a Description</span>
            </div>
            <textarea name="spellDescription" id="spellDescription" class="form-control" rows="3" ng-model="spell.Description" required></textarea>
        </div>

        @*Submit*@
        <div class="form-group">
            <input type="button"
                   value="Add"
                   class="btn btn-default"
                   data-toggle="modal"
                   data-target="#myModal"
                   ng-disabled="!form.$valid"
                   ng-click="addSpell()" />
            <span class="label label-danger" ng-show="!form.$valid">Watch Out! You're Missing Some Spell Data!</span>
        </div>

    </form>

    <!-- Modal -->
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-body">
                    <h2>Loading...</h2>
                    <div class="progress progress-striped active">
                        <div class="progress-bar" role="progressbar" aria-valuenow="45" aria-valuemin="0" aria-valuemax="100" style="width: 45%">
                            <span class="sr-only">45% Complete</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>

DungeonResource.Web/Views/Spell/Details.cshtml
@model DungeonResource.Components.Domain.Spell.Spell

@{
    ViewBag.Title = "Details";
}

<div class="form-signin">

    <h2>@Model.Name</h2>
    <ul class="unstyled">
        <li>
            <b>Spell Level</b>
            @foreach (var item in @Model.SpellLevels)
            {
                @item.SpellClass <i>@item.Level</i>
            }
        </li>
        <li><b>Spell Resistance</b> @(Model.SpellResistance ? "Yes" : "No")</li>
        <li><b>Duration</b> @Model.Duration</li>
        <li><b>Targets</b> @Model.Targets</li>
        <li><b>Casting Time</b> @Model.CastingTime</li>
        <li><b>Range</b> @Model.Range.ToString()</li>
        <li><b>Saving Throw</b> @(@Model.SavingThrow ? "Yes" : "No")</li>

        <li>
            <b>Component</b>
            @((Model.Verbal) ? "Verbal" : "")
            @((Model.Somatic) ? "Somatic" : "")
            @((Model.Material) ? "Material" : "")
            @((Model.Focus) ? "Focus" : "")
        </li>

    </ul>

    <h3>Spell Details</h3>

    <pre>
@Model.Description
</pre>

    @if (Request.IsAuthenticated)
    {

        <ul class="unstyled">
            <li><b>Last Edited</b> @(Model.Editor ?? "System") - @((Model.LastEdited != DateTime.MinValue) ? Model.LastEdited.ToString() : "The Beginning")</li>
        </ul>

        <a href='/spell/update/@Model.Id' class="btn btn-default">Edit Spell</a>
        <a href="#myModal" role="button" class="btn btn-danger" data-toggle="modal">Delete Spell</a>

        <!-- Modal -->
        <div id="myModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h3 id="myModalLabel">Are You Sure?</h3>
            </div>
            <div class="modal-body">
                <p>Removing this spell can lead to some unecessary downtime for the users. Are you sure you want to do this?</p>
            </div>
            <div class="modal-footer">
                <button class="btn btn-inverse" data-dismiss="modal" aria-hidden="true">Cancel</button>
                <a href='@Url.Action("Delete", "Spell", new { id = Model.Id })' class="btn btn-danger">Delete Spell</a>
            </div>
        </div>

    }

</div>

DungeonResource.Web/Views/Spell/Index.cshtml
@model IEnumerable<DungeonResource.Components.Domain.Spell.Spell>

@{
    ViewBag.Title = "Dungeon Resource";
}

<div class="form-signin">

    <h2>@ViewBag.Title</h2>

    <h3>Manage All Your Spells With Ease</h3>

    <p>
        With SpellBook You Can Easily Research All the Spells Available
        to You for Dungeons and Dragons. Search for technical details for that hard to
        find spell and make it out of the Dungeon Alive
    </p>

    <br />

    <div class="panel-group" id="accordion">

        @foreach (var someClass in @Model.SelectMany(p => p.SpellLevels).Select(p => p.SpellClass).OrderBy(x => x).Distinct())
        {
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h4 class="panel-title">
                        <a data-toggle="collapse" data-parent="#accordion" href="#collapse-@(someClass.Replace(" ", ""))">@someClass</a>
                    </h4>
                </div>

                <div id="collapse-@(someClass.Replace(" ", ""))" class="panel-collapse collapse">
                    <div class="panel-body">
                        <table class="table table-hover">
                            <thead>
                                <tr>
                                    <th>Spell Name</th>
                                    <th>Range</th>
                                    <th>Spell Resistance</th>
                                    <th>Level</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model.Where(p => p.SpellLevels.Exists(r => r.SpellClass == someClass)).OrderBy(p => p.Name))
                                {
                                    <tr>
                                        <td>@Html.ActionLink(item.Name, "Details", new { ID = item.Id })</td>
                                        <td>@item.Range</td>
                                        <td>@(item.SpellResistance ? "Yes" : "No")</td>
                                        <td>@item.SpellLevels[0].Level</td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        }

        @if (Request.IsAuthenticated)
        {
            <br />
            <a href="@Url.Action("Create")" class="btn btn-default btn-lg btn-block">Add Spell</a>
        }

    </div>

</div>

DungeonResource.Web/Views/Spell/Update.cshtml
@{
    ViewBag.Title = "Update";
}


<div class="form-signin" ng-app="myApp" ng-controller="UpdateSpellController">

    <h2>Update Spell</h2>

    <br />

    <form role="form" name="form" ng-init="readSpell()">

        @*Spell Name*@
        <div class="form-group" ng-class="{'has-error': (form.spellName.$dirty && form.spellName.$invalid)}">
            <div>
                <label for="spellName">Spell Name</label>
                <span ng-show="form.spellName.$dirty && form.spellName.$invalid" class="label label-danger">Please Enter a Spell Name</span>
            </div>
            <input type="text"
                   class="form-control"
                   name="spellName"
                   id="spellName"
                   placeholder="Enter spell name"
                   ng-model="spell.Name"
                   required>
        </div>

        @*Target*@
        <div class="form-group" ng-class="{'has-error': (form.spellTarget.$dirty && form.spellTarget.$invalid)}">
            <div>
                <label for="spellTarget">Target</label>
                <span ng-show="form.spellTarget.$dirty && form.spellTarget.$invalid" class="label label-danger">Please Enter a Target</span>
            </div>
            <input type="text"
                   class="form-control"
                   name="spellTarget"
                   id="spellTarget"
                   placeholder="Enter spell target"
                   ng-model="spell.Targets"
                   required>
        </div>

        @*Casting Time*@
        <div class="form-group" ng-class="{'has-error': (form.spellCastingTime.$dirty && form.spellCastingTime.$invalid)}">
            <div>
                <label for="spellCastingTime">Casting Time</label>
                <span ng-show="form.spellCastingTime.$dirty && form.spellCastingTime.$invalid" class="label label-danger">Please Enter a Casting Time</span>
            </div>
            <input type="text" class="form-control" name="spellCastingTime" id="spellCastingTime" placeholder="Enter casting time" ng-model="spell.CastingTime" required>
        </div>

        @*Duration*@
        <div class="form-group" ng-class="{'has-error': (form.spellDuration.$dirty && form.spellDuration.$invalid)}">
            <div>
                <label for="spellDuration">Duration</label>
                <span ng-show="form.spellDuration.$dirty && form.spellDuration.$invalid" class="label label-danger">Please Enter a Spell Duration</span>
            </div>
            <input type="text" class="form-control" name="spellDuration" id="spellDuration" placeholder="Enter spell duration" ng-model="spell.Duration" required>
        </div>

        @*Range*@
        <div class="form-group">
            <div>
                <label>Spell Range</label>
            </div>
            <div class="btn-group">
                <label class="btn btn-default">
                    <input type="radio" name="spellRange" data-ng-model="spell.Range" value="0"> Self
                </label>
                <label class="btn btn-default">
                    <input type="radio" name="spellRange" data-ng-model="spell.Range" value="1"> Touch
                </label>
                <label class="btn btn-default">
                    <input type="radio" name="spellRange" data-ng-model="spell.Range" value="2"> Close
                </label>
                <label class="btn btn-default">
                    <input type="radio" name="spellRange" data-ng-model="spell.Range" value="3"> Medium
                </label>
                <label class="btn btn-default">
                    <input type="radio" name="spellRange" data-ng-model="spell.Range" value="4"> Long
                </label>
            </div>
        </div>

        @*Attributes*@
        <div class="form-group">
            <div>
                <label for="spellImportant">Important</label>
            </div>
            <div class="btn-group" id="spellImportant">
                <label class="btn btn-default">
                    <input ng-model="spell.SpellResistance" type="checkbox"> Spell Resistance
                </label>
                <label class="btn btn-default">
                    <input ng-model="spell.SavingThrow" type="checkbox"> Saving Throw
                </label>
            </div>
        </div>

        @*Components*@
        <div class="form-group">
            <div>
                <label for="spellComponents">Components</label>
            </div>
            <div class="btn-group" id="spellComponents">
                <label class="btn btn-default">
                    <input ng-model="spell.Verbal" type="checkbox"> Verbal
                </label>
                <label class="btn btn-default">
                    <input ng-model="spell.Somatic" type="checkbox"> Somatic
                </label>
                <label class="btn btn-default">
                    <input ng-model="spell.Material" type="checkbox"> Material
                </label>
                <label class="btn btn-default">
                    <input ng-model="spell.Focus" type="checkbox"> Focus
                </label>
            </div>
        </div>

        @*Class Levels*@
        <div class="form-group">
            <div>
                <label for="spellClassLevels">Classes</label>
            </div>
            <table class="table table-striped table-hover">
                <thead>
                    <tr>
                        <th>Class Name</th>
                        <th>Level</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    <tr ng-repeat="spellLevel in spell.SpellLevels">
                        <td>{{spellLevel.SpellClass}}</td>
                        <td>{{spellLevel.Level}}</td>
                        <td><a href="" class="btn btn-default" ng-click="remove(spell.SpellLevels, $index)">Remove</a></td>
                    </tr>
                </tbody>
            </table>
        </div>

        <div class="form-group">
            <div class="form-inline">
                <div class="form-group">
                    <input type="text" id="className" placeholder="Class Name" ng-model="spellClass" />
                </div>
                <div class="form-group">
                    <input type="number" id="spellLevel" placeholder="Class Level" ng-model="spellLevel" />
                </div>
                <div class="form-group">
                    <a href="" class="btn btn-default" ng-click="addSpellLevel()">Add</a>
                </div>
            </div>
        </div>

        @*Description*@
        <div class="form-group" ng-class="{'has-error': (form.spellDescription.$dirty && form.spellDescription.$invalid)}">
            <div>
                <label for="spellDescription">Description</label>
                <span ng-show="form.spellDescription.$dirty && form.spellDescription.$invalid" class="label label-danger">Please Enter a Description</span>
            </div>
            <textarea name="spellDescription" id="spellDescription" class="form-control" rows="3" ng-model="spell.Description" required></textarea>
        </div>

        @*Submit*@
        <div class="form-group">
            <input type="button"
                   value="Update"
                   class="btn btn-default"
                   data-toggle="modal"
                   data-target="#myModal"
                   ng-disabled="!form.$valid"
                   ng-click="updateSpell()" />
            <span class="label label-danger" ng-show="!form.$valid">Watch Out! You're Missing Some Spell Data!</span>
        </div>

    </form>

    <!-- Modal -->
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-body">
                    <h2>Loading...</h2>
                    <div class="progress progress-striped active">
                        <div class="progress-bar" role="progressbar" aria-valuenow="45" aria-valuemin="0" aria-valuemax="100" style="width: 45%">
                            <span class="sr-only">45% Complete</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>